language: c

env:
  global:
    - TARGET_DIR=bin
  matrix:
    - TARGET=cpp
    - TARGET=cs
    - TARGET=flash
    - TARGET=java
    - TARGET=js
    - TARGET=neko
    - TARGET=php
    - TARGET=python

matrix:
  fast_finish: true

before_install: # clone travis-hx repo
  - travis_retry git clone --depth=50 --branch=master git://github.com/waneck/travis-hx.git ~/travis-hx

install: # setup the target
  - ~/travis-hx/setup.sh

script:
  - cd $TRAVIS_BUILD_DIR
  - haxe hxml/$TARGET.hxml -D travis
  # run the tests
  - ~/travis-hx/runtests.sh $FILENAME # this will set the $FILENAME defined on the environment variable to run the tests
