sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
  - "3.4.7"
  - "4.0.5"
  - "4.1.0"
  - development

install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix interp
  - haxelib run travix neko
  - haxelib run travix python
  - haxelib run travix node
  # - haxelib run travix flash # Failing
  # - haxelib run travix js
  - haxelib run travix java
  - if ! [ "$TRAVIS_HAXE_VERSION" == "3.2.1" ]; then haxelib run travix cpp; fi
  - haxelib run travix cs
  #Fails to install php on both Linux & OSX: https://github.com/back2dos/travix/issues/114
  # - haxelib run travix php
  - if [ `uname` = "Linux" ] && ! [ "$TRAVIS_HAXE_VERSION" == "3.2.1" ]; then haxelib run travix lua; fi;

