sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
  - "3.2.1"
  - "3.4.7"
  - development

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix interp
  - haxelib run travix neko
  - haxelib run travix python
  - haxelib run travix node
  # - haxelib run travix flash # Failing
  # - haxelib run travix js #Need to check against phantomjs
  - haxelib run travix java
  - if ! [ "$TRAVIS_HAXE_VERSION" == "3.2.1" ]; then haxelib run travix cpp; fi
  - haxelib run travix cs
  #Fails to install php on OSX
  - if [ `uname` = "Linux" ]; then haxelib run travix php; fi;
  #Invalid lua setup on OSX. See https://github.com/back2dos/travix/issues/78
  # - if [ `uname` = "Linux" ] && ! [ "$TRAVIS_HAXE_VERSION" == "3.2.1" ]; then haxelib run travix lua; fi;

